#  _______                _______ _  _       _             ______    _____  
# (_______)              (_______) |(_)     | |           (_____ \  (_____) 
#     _  ____ _____ _____ _      | | _  ____| |  _    _   _ ____) ) _  __ _ 
#    | |/ ___) ___ | ___ | |     | || |/ ___) |_/ )  | | | / ____/ | |/ /| |
#    | | |   | ____| ____| |_____| || ( (___|  _ (    \ V / (_____ |   /_| |
#    |_|_|   |_____)_____)\______)\_)_|\____)_| \_)    \_/|_______|_)_____/ 


# Plugin that allows players to instantly cut down entire trees with a single click

## Main plugin toggle
enabled: true

## World settings
worlds:
  # Define which worlds the plugin should be active in
  enabled_worlds:
    - world
    - world_nether
  # Set to true to enable the plugin in all worlds
  all_worlds: true

# Tree cutting behavior
cutting:
  require_axe: true
  # If true, entire tree will be chopped instantly
  require_leaves: true  
  # If true, standalone logs won't be cut down - only trees with more leaves than logs in the trunk.
  instant_chop: true
  # If true, tree will be instantly cut down
  cutting_speed: 0
  # If set to 0, the cutting speed is based on the player's axe. Otherwise this specifies how fast in ticks each layer of wood will be cut
  drop_to_inventory: false
  # Drop loot directly to player inventory
  replant_saplings: true
  
# Tree type definitions - each tree has its own leaf, log, and sapling type
  trees:
    oak:
      leaf_block: OAK_LEAVES
      log_block: OAK_LOG
      sapling: OAK_SAPLING
    spruce:
      leaf_block: SPRUCE_LEAVES
      log_block: SPRUCE_LOG
      sapling: SPRUCE_SAPLING
    birch:
      leaf_block: BIRCH_LEAVES
      log_block: BIRCH_LOG
      sapling: BIRCH_SAPLING
    jungle:
      leaf_block: JUNGLE_LEAVES
      log_block: JUNGLE_LOG
      sapling: JUNGLE_SAPLING
    acacia:
      leaf_block: ACACIA_LEAVES
      log_block: ACACIA_LOG
      sapling: ACACIA_SAPLING
    dark_oak:
      leaf_block: DARK_OAK_LEAVES
      log_block: DARK_OAK_LOG
      sapling: DARK_OAK_SAPLING
    mangrove:
      leaf_block: MANGROVE_LEAVES
      log_block: MANGROVE_LOG
      sapling: MANGROVE_PROPAGULE
    cherry:
      leaf_block: CHERRY_LEAVES
      log_block: CHERRY_LOG
      sapling: CHERRY_SAPLING
    crimson:
      leaf_block: NETHER_WART_BLOCK
      log_block: CRIMSON_STEM
      sapling: CRIMSON_FUNGUS
    warped:
      leaf_block: WARPED_WART_BLOCK
      log_block: WARPED_STEM
      sapling: WARPED_FUNGUS
    pale_oak:
      leaf_block: PALE_OAK_LEAVES
      log_block: PALE_OAK_LOG
      sapling: PALE_OAK_SAPLING
  
## Safety blocks
# These are the wood variants with bark on all faces. If the plugin detects these on a tree, it will immediately stop and assume that you are destroying a decorative tree
safety:
    safe_blocks:
        - OAK_WOOD
        - SPRUCE_WOOD
        - BIRCH_WOOD
        - JUNGLE_WOOD
        - ACACIA_WOOD
        - CRIMSON_HYPHAE
        - DARK_OAK_WOOD
        - PALE_OAK_WOOD
        - MANGROVE_WOOD
        - CHERRY_WOOD
        - WARPED_HYPHAE
        
# Permissions
permissions:
  use: "treeclick.use"